version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "prisma-pg"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=prisma
    ports:
      - "54320:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
